name: Deployment Workflow

on:
  push:
    branches: [ master ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: testing stonks ssh connection
      uses: appleboy/ssh-action@master
      with:
        host: 192.168.1.213
        username: sstoveld
        key: ${{ secrets.STONKS_SECRET }}
        port: 22
        script: |
          cd stonks-only-go-up
          git pull origin master
          git status
