name: Deployment Workflow

on:
  push:
    branches: [ main ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: testing stonks ssh connection
      uses: fifsky/ssh-action@master
      with:
        host: ${{ secrets.HOST_SECRET }}
        user: sstoveld
        key: ${{ secrets.STONKS_SECRET }}
        port: 22
        command: |
          cd /home/sstoveld/stonks-only-go-up
          git pull origin main
